/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package CapaCliente;

import CapaLogica.clsTipoVehiculo;
import CapaLogica.clsVehiculo;
import java.sql.ResultSet;
import java.util.Comparator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mercurio5
 */
public class JdMatenimientoVehiculo extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JdMatenimientoVehiculo.class.getName());
    clsVehiculo objVehiculo = new clsVehiculo();
    clsTipoVehiculo objTipoVehiculo = new clsTipoVehiculo();
    FrmMenuPrincipal frmP;

    /**
     * Creates new form JdMatenimientoVehiculo
     */
    public JdMatenimientoVehiculo(java.awt.Frame parent, boolean modal, FrmMenuPrincipal frmP) {
        super(parent, modal);
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProducto = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscador = new javax.swing.JTextField();
        btnGestionarPersona = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVehiculo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pnlProducto.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setText("Mantenimiento de Vehículo");

        txtbuscador.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N

        btnGestionarPersona.setBackground(new java.awt.Color(31, 41, 55));
        btnGestionarPersona.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnGestionarPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionarPersona.setText("Administrar Vehiculos");
        btnGestionarPersona.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarPersonaActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(31, 41, 55));
        btnBuscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar Por Placa");
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblVehiculo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tblVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblVehiculo);

        jLabel1.setText("**");

        javax.swing.GroupLayout pnlProductoLayout = new javax.swing.GroupLayout(pnlProducto);
        pnlProducto.setLayout(pnlProductoLayout);
        pnlProductoLayout.setHorizontalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlProductoLayout.createSequentialGroup()
                        .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(pnlProductoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(499, 499, 499))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlProductoLayout.createSequentialGroup()
                                .addComponent(txtbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(279, 279, 279)
                                .addComponent(btnGestionarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))))
        );
        pnlProductoLayout.setVerticalGroup(
            pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGestionarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listar() {
        DefaultTableModel mdl = new DefaultTableModel();
        mdl.addColumn("ID");
        mdl.addColumn("Placa");
        mdl.addColumn("Año fabricacion");
        mdl.addColumn("modelo");
        mdl.addColumn("nro. doc. Cliente");
        ResultSet rs = null;
        try {
            rs = objVehiculo.listarVehiculo();
            while (rs.next()) {
                mdl.addRow(new Object[]{
                    rs.getString("idVehiculo"),
                    rs.getString("placa"),
                    rs.getString("anofabricacion"),
                    rs.getString("modelovehiculo"),
                    rs.getString("numdocumento")
                });
                tblVehiculo.setModel(mdl);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al listar \n" + e.getMessage());
        }

    }

    private void btnGestionarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarPersonaActionPerformed
        JdGestionarVehiculo obj = new JdGestionarVehiculo(frmP, true);
        obj.setLocationRelativeTo(frmP);
        obj.setVisible(true);
    }//GEN-LAST:event_btnGestionarPersonaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel mdl = new DefaultTableModel();
        mdl.addColumn("ID");
        mdl.addColumn("Placa");
        mdl.addColumn("Año fabricacion");
        mdl.addColumn("modelo");
        mdl.addColumn("nro. doc. Cliente");
        ResultSet rs = null;
        if (txtbuscador.getText().isBlank()) {
            listar();
        } else {
            try {
                rs = objVehiculo.buscarPLacaTotal(txtbuscador.getText());
                if (rs.next()) {
                    mdl.addRow(new Object[]{
                        rs.getString("idVehiculo"),
                        rs.getString("placa"),
                        rs.getString("anofabricacion"),
                        rs.getString("modelovehiculo"),
                        rs.getString("numdocumento")
                    });
                            }else{
                JOptionPane.showMessageDialog(rootPane,"No se encontro ninguna coincidencia");
                }
                tblVehiculo.setModel(mdl);
                }catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

            }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
         * @param args the command line arguments
         */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGestionarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlProducto;
    private javax.swing.JTable tblVehiculo;
    private javax.swing.JTextField txtbuscador;
    // End of variables declaration//GEN-END:variables
}
